# Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

In [4]:
a = np.zeros(10)

In [5]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a[5] = 1

In [7]:
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# Create a vector with values ranging from 10 to 49

In [10]:
a=np.arange(10,50)


In [11]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#  Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
a = np.arange(9).reshape(3,3)

In [13]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#  Find indices of non-zero elements from [1,2,0,0,4,0] 

In [20]:
a = np.nonzero([1,2,0,0,4,0])

In [21]:
a

(array([0, 1, 4], dtype=int64),)

#   Create a 10x10 array with random values and find the minimum and maximum values.

In [22]:
a = np.random.random(10)

In [23]:
a

array([0.97972886, 0.42674887, 0.967052  , 0.28273041, 0.84270004,
       0.75967317, 0.72049549, 0.91620918, 0.64577936, 0.65608527])

#  Create a random vector of size 30 and find the mean value.


In [26]:
Z = np.random.random(30)
m = Z.mean()
print (m)

0.41742815468815514
